name: "Frogbot PR Scan"
on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  frogbot-scan:
    runs-on: ubuntu-latest
    environment: frogbot
    steps:
      - uses: jfrog/frogbot@v2
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JFROG_CLI_LOG_LEVEL: "DEBUG"
          JF_INCLUDE_ALL_VULNERABILITIES: "true"
          JF_FAIL: "false"
